version: "2.3"
services:
  {{CONTAINER_NAME}}:
    volumes:
      - ./server_files:/home/gsc/server_files
      - ./post_install:/home/gsc/post_install
    build:
      context: .
      args:
        uid: {{FORCE_UID}} ${uid}
    env_file:
      - vars.env
    {{PORTS}}
    mem_limit: {{MEM_LIMIT}}
    cpu_percent: {{CPU_PERCENT}}
