- hosts: all
  gather_facts: false
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt-get update && apt-get install -y python-minimal python-apt)
    - setup:
  roles:
    - gsc-user #https://github.com/Egeeio/gsc-user
