version: "2.3"
services:
  7days-server:
    volumes:
      - type: bind
        source: ./server_files/
        target: /home/gsc/server_files
    mem_reservation: 1024m
    build:
      context: .
      args:
        uid: ${uid}
    ports:
      - "8080:8080/tcp"
      - "26900:26900/tcp"
      - "26900:26900/udp"
      - "26901:26901/udp"
      - "26902:26902/udp"
