version: "3.2"
services:
  tf2-server:
    volumes:
      - type: bind
        source: ./server_files/
        target: /home/gsc/server_files
    # mem_reservation: 2048m
    # cpu_shares: 100
    build:
      context: .
      args:
        uid: ${uid}
    ports:
      - "27015:27015/udp"
      - "27005:27005/udp"
