version: "2.3"
services:
  rust-server:
    volumes:
      - type: bind
        source: ./server_files/
        target: /home/gsc/server_files
    mem_reservation: 2048m
    build:
      context: .
      args:
        uid: ${uid}
    env_file:
      - vars.env
    ports:
      - "28015:28015/udp"
      - "28016:28016"
