version: "2.3"
services:
  rust-server:
    volumes:
      - type: bind
        source: ./rust/
        target: /opt/rustserver/server/rust
      - type: bind
        source: ./rust/server.log
        target: /opt/rustserver/server.log
    # mem_reservation: 1024m
    # cpu_shares: 1024
    # cpus: 1
    build:
      context: .
    env_file:
      - vars.env
    ports:
    - "28015:28015/udp"
    - "28016:28016"
