version: "2.3"
services:
  minecraft-server:
    cpuset: '1'
    mem_reservation: 3048m
    volumes:
      - type: bind
        source: ./server_files/
        target: /home/gsc/server_files
    build:
      context: .
      args:
        uid: ${uid}
    ports:
      - "25565:25565"
      - "25575:25575"
