version: "2.3"
services:
  terraria-server:
    volumes:
      - type: bind
        source: ./server_files/
        target: /home/gsc/server_files
    stdin_open: true
    tty: true
    # mem_reservation: 1024m
    # cpu_shares: 1024
    # cpus: 1
    build:
      context: .
      args:
        uid: ${uid}
    ports:
      - "7777:7777"
