version: "2.3"
services:
  aceofspades-server:
    volumes:
      - type: bind
        source: ./server_files/
        target: /home/gsc/server_files
    # mem_reservation: 1024m
    # cpu_shares: 1024
    # cpus: 1
    build:
      context: .
      args:
        uid: ${uid}
    ports:
      - "25574:25574/udp" #Port for game
      - "32886:32886" #Web Monitor
      - "32885:32885" #Ban Publishing
